version: '3'
services:
        jupyter:
                build: .
                ports:
                        - "8888:8888"
                        - "8082:8082"
                volumes:
                        - ./:/emp_priv
                shm_size: 4G
